#  GLUI_INCLUDE_DIR, where to find GL/glui.h, etc.
#  GLUI_LIBRARIES, the libraries to link against
#  GLUI_FOUND, If false, do not try to use GLUI.

SET( GLUI_FOUND FALSE )
FIND_PATH( GLUI_INCLUDE_DIR GL/glui.h )

IF(WIN32)
  FIND_LIBRARY( GLUI_LIBRARIES glui32 )
  FIND_LIBRARY( GLUI_LIBRARIES_DEBUG glui32d )
ELSE(WIN32)
  FIND_LIBRARY( GLUI_LIBRARIES glui )
ENDIF(WIN32)

IF (GLUI_LIBRARIES)
  SET( GLUI_FOUND "YES" )
ENDIF(GLUI_LIBRARIES)

MARK_AS_ADVANCED(
	GLUI_INCLUDE_DIR
	GLUI_LIBRARIES
	GLUI_LIBRARIES_DEBUG
)
